/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as EncargosRouteImport } from './routes/encargos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EncargosIndexRouteImport } from './routes/encargos.index'
import { Route as TiendaReservadoRouteImport } from './routes/tienda.reservado'
import { Route as TiendaPagoCompletadoRouteImport } from './routes/tienda.pago-completado'
import { Route as TiendaSlugRouteImport } from './routes/tienda.$slug'
import { Route as EncargosPagoCompletadoRouteImport } from './routes/encargos.pago-completado'
import { Route as AuthenticatedProductosRouteImport } from './routes/_authenticated/productos'
import { Route as AuthenticatedPagosRouteImport } from './routes/_authenticated/pagos'
import { Route as AuthenticatedGaleriaAdminRouteImport } from './routes/_authenticated/galeria-admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as EncargosPagarTokenRouteImport } from './routes/encargos.pagar.$token'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const EncargosRoute = EncargosRouteImport.update({
  id: '/encargos',
  path: '/encargos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EncargosIndexRoute = EncargosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EncargosRoute,
} as any)
const TiendaReservadoRoute = TiendaReservadoRouteImport.update({
  id: '/reservado',
  path: '/reservado',
  getParentRoute: () => TiendaRoute,
} as any)
const TiendaPagoCompletadoRoute = TiendaPagoCompletadoRouteImport.update({
  id: '/pago-completado',
  path: '/pago-completado',
  getParentRoute: () => TiendaRoute,
} as any)
const TiendaSlugRoute = TiendaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TiendaRoute,
} as any)
const EncargosPagoCompletadoRoute = EncargosPagoCompletadoRouteImport.update({
  id: '/pago-completado',
  path: '/pago-completado',
  getParentRoute: () => EncargosRoute,
} as any)
const AuthenticatedProductosRoute = AuthenticatedProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagosRoute = AuthenticatedPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGaleriaAdminRoute =
  AuthenticatedGaleriaAdminRouteImport.update({
    id: '/galeria-admin',
    path: '/galeria-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EncargosPagarTokenRoute = EncargosPagarTokenRouteImport.update({
  id: '/pagar/$token',
  path: '/pagar/$token',
  getParentRoute: () => EncargosRoute,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/encargos': typeof EncargosRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tienda': typeof TiendaRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/galeria-admin': typeof AuthenticatedGaleriaAdminRoute
  '/pagos': typeof AuthenticatedPagosRoute
  '/productos': typeof AuthenticatedProductosRoute
  '/encargos/pago-completado': typeof EncargosPagoCompletadoRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/tienda/pago-completado': typeof TiendaPagoCompletadoRoute
  '/tienda/reservado': typeof TiendaReservadoRoute
  '/encargos/': typeof EncargosIndexRoute
  '/encargos/pagar/$token': typeof EncargosPagarTokenRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tienda': typeof TiendaRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/galeria-admin': typeof AuthenticatedGaleriaAdminRoute
  '/pagos': typeof AuthenticatedPagosRoute
  '/productos': typeof AuthenticatedProductosRoute
  '/encargos/pago-completado': typeof EncargosPagoCompletadoRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/tienda/pago-completado': typeof TiendaPagoCompletadoRoute
  '/tienda/reservado': typeof TiendaReservadoRoute
  '/encargos': typeof EncargosIndexRoute
  '/encargos/pagar/$token': typeof EncargosPagarTokenRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/encargos': typeof EncargosRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tienda': typeof TiendaRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/galeria-admin': typeof AuthenticatedGaleriaAdminRoute
  '/_authenticated/pagos': typeof AuthenticatedPagosRoute
  '/_authenticated/productos': typeof AuthenticatedProductosRoute
  '/encargos/pago-completado': typeof EncargosPagoCompletadoRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/tienda/pago-completado': typeof TiendaPagoCompletadoRoute
  '/tienda/reservado': typeof TiendaReservadoRoute
  '/encargos/': typeof EncargosIndexRoute
  '/encargos/pagar/$token': typeof EncargosPagarTokenRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contacto'
    | '/encargos'
    | '/galeria'
    | '/privacidad'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tienda'
    | '/dashboard'
    | '/galeria-admin'
    | '/pagos'
    | '/productos'
    | '/encargos/pago-completado'
    | '/tienda/$slug'
    | '/tienda/pago-completado'
    | '/tienda/reservado'
    | '/encargos/'
    | '/encargos/pagar/$token'
    | '/api/public/media/$'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contacto'
    | '/galeria'
    | '/privacidad'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tienda'
    | '/dashboard'
    | '/galeria-admin'
    | '/pagos'
    | '/productos'
    | '/encargos/pago-completado'
    | '/tienda/$slug'
    | '/tienda/pago-completado'
    | '/tienda/reservado'
    | '/encargos'
    | '/encargos/pagar/$token'
    | '/api/public/media/$'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contacto'
    | '/encargos'
    | '/galeria'
    | '/privacidad'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tienda'
    | '/_authenticated/dashboard'
    | '/_authenticated/galeria-admin'
    | '/_authenticated/pagos'
    | '/_authenticated/productos'
    | '/encargos/pago-completado'
    | '/tienda/$slug'
    | '/tienda/pago-completado'
    | '/tienda/reservado'
    | '/encargos/'
    | '/encargos/pagar/$token'
    | '/api/public/media/$'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactoRoute: typeof ContactoRoute
  EncargosRoute: typeof EncargosRouteWithChildren
  GaleriaRoute: typeof GaleriaRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TiendaRoute: typeof TiendaRouteWithChildren
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encargos': {
      id: '/encargos'
      path: '/encargos'
      fullPath: '/encargos'
      preLoaderRoute: typeof EncargosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encargos/': {
      id: '/encargos/'
      path: '/'
      fullPath: '/encargos/'
      preLoaderRoute: typeof EncargosIndexRouteImport
      parentRoute: typeof EncargosRoute
    }
    '/tienda/reservado': {
      id: '/tienda/reservado'
      path: '/reservado'
      fullPath: '/tienda/reservado'
      preLoaderRoute: typeof TiendaReservadoRouteImport
      parentRoute: typeof TiendaRoute
    }
    '/tienda/pago-completado': {
      id: '/tienda/pago-completado'
      path: '/pago-completado'
      fullPath: '/tienda/pago-completado'
      preLoaderRoute: typeof TiendaPagoCompletadoRouteImport
      parentRoute: typeof TiendaRoute
    }
    '/tienda/$slug': {
      id: '/tienda/$slug'
      path: '/$slug'
      fullPath: '/tienda/$slug'
      preLoaderRoute: typeof TiendaSlugRouteImport
      parentRoute: typeof TiendaRoute
    }
    '/encargos/pago-completado': {
      id: '/encargos/pago-completado'
      path: '/pago-completado'
      fullPath: '/encargos/pago-completado'
      preLoaderRoute: typeof EncargosPagoCompletadoRouteImport
      parentRoute: typeof EncargosRoute
    }
    '/_authenticated/productos': {
      id: '/_authenticated/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof AuthenticatedProductosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagos': {
      id: '/_authenticated/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof AuthenticatedPagosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/galeria-admin': {
      id: '/_authenticated/galeria-admin'
      path: '/galeria-admin'
      fullPath: '/galeria-admin'
      preLoaderRoute: typeof AuthenticatedGaleriaAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/encargos/pagar/$token': {
      id: '/encargos/pagar/$token'
      path: '/pagar/$token'
      fullPath: '/encargos/pagar/$token'
      preLoaderRoute: typeof EncargosPagarTokenRouteImport
      parentRoute: typeof EncargosRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGaleriaAdminRoute: typeof AuthenticatedGaleriaAdminRoute
  AuthenticatedPagosRoute: typeof AuthenticatedPagosRoute
  AuthenticatedProductosRoute: typeof AuthenticatedProductosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGaleriaAdminRoute: AuthenticatedGaleriaAdminRoute,
  AuthenticatedPagosRoute: AuthenticatedPagosRoute,
  AuthenticatedProductosRoute: AuthenticatedProductosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EncargosRouteChildren {
  EncargosPagoCompletadoRoute: typeof EncargosPagoCompletadoRoute
  EncargosIndexRoute: typeof EncargosIndexRoute
  EncargosPagarTokenRoute: typeof EncargosPagarTokenRoute
}

const EncargosRouteChildren: EncargosRouteChildren = {
  EncargosPagoCompletadoRoute: EncargosPagoCompletadoRoute,
  EncargosIndexRoute: EncargosIndexRoute,
  EncargosPagarTokenRoute: EncargosPagarTokenRoute,
}

const EncargosRouteWithChildren = EncargosRoute._addFileChildren(
  EncargosRouteChildren,
)

interface TiendaRouteChildren {
  TiendaSlugRoute: typeof TiendaSlugRoute
  TiendaPagoCompletadoRoute: typeof TiendaPagoCompletadoRoute
  TiendaReservadoRoute: typeof TiendaReservadoRoute
}

const TiendaRouteChildren: TiendaRouteChildren = {
  TiendaSlugRoute: TiendaSlugRoute,
  TiendaPagoCompletadoRoute: TiendaPagoCompletadoRoute,
  TiendaReservadoRoute: TiendaReservadoRoute,
}

const TiendaRouteWithChildren =
  TiendaRoute._addFileChildren(TiendaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactoRoute: ContactoRoute,
  EncargosRoute: EncargosRouteWithChildren,
  GaleriaRoute: GaleriaRoute,
  PrivacidadRoute: PrivacidadRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TiendaRoute: TiendaRouteWithChildren,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
